-- ============================================================
-- ChowApp — Nigerian Food Database
-- Unit 2: Dish Seed Data
-- 108 dishes | Version 1.0.0
-- ============================================================

-- SCHEMA
CREATE TABLE IF NOT EXISTS dishes (
  dish_id          VARCHAR(6)    PRIMARY KEY,
  slug             VARCHAR(100)  NOT NULL UNIQUE,
  name_english     VARCHAR(200)  NOT NULL,
  name_local       TEXT,
  category         VARCHAR(50)   NOT NULL,
  region           VARCHAR(100)  NOT NULL,
  ethnic_group     VARCHAR(100)  NOT NULL,
  primary_ingredients  TEXT[]    NOT NULL,
  taste_profile    TEXT[]        NOT NULL,
  description      TEXT          NOT NULL,
  pairs_with       TEXT[]        DEFAULT '{}',
  vegan            BOOLEAN       DEFAULT FALSE,
  vegetarian       BOOLEAN       DEFAULT FALSE,
  halal            BOOLEAN       DEFAULT TRUE,
  contains_pork    BOOLEAN       DEFAULT FALSE,
  contains_shellfish BOOLEAN     DEFAULT FALSE,
  spice_level      SMALLINT      CHECK (spice_level BETWEEN 0 AND 5),
  prep_time_mins   INTEGER,
  image_url        VARCHAR(300),
  created_at       TIMESTAMPTZ   DEFAULT NOW(),
  updated_at       TIMESTAMPTZ   DEFAULT NOW()
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_dishes_category ON dishes(category);
CREATE INDEX IF NOT EXISTS idx_dishes_region ON dishes(region);
CREATE INDEX IF NOT EXISTS idx_dishes_ethnic_group ON dishes(ethnic_group);
CREATE INDEX IF NOT EXISTS idx_dishes_slug ON dishes(slug);
CREATE INDEX IF NOT EXISTS idx_dishes_halal ON dishes(halal);
CREATE INDEX IF NOT EXISTS idx_dishes_vegan ON dishes(vegan);
CREATE INDEX IF NOT EXISTS idx_dishes_spice ON dishes(spice_level);

-- SEED DATA
INSERT INTO dishes (
  dish_id, slug, name_english, name_local, category, region, ethnic_group,
  primary_ingredients, taste_profile, description, pairs_with,
  vegan, vegetarian, halal, contains_pork, contains_shellfish,
  spice_level, prep_time_mins, image_url
) VALUES
  ('D001', 'egusi-soup', 'Egusi Soup', 'Ofe Egusi (Igbo), Efo Elegusi (Yoruba), Miyan Gushi (Hausa)',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['melon seeds', 'palm oil', 'leafy greens', 'assorted meat', 'stockfish', 'crayfish', 'pepper'], ARRAY['Rich', 'Earthy', 'Spicy'],
   'Nigeria''s most popular soup, made from ground melon seeds cooked in palm oil with leafy greens and assorted meats. Bold, filling, and deeply satisfying — the undisputed king of Nigerian soups.',
   ARRAY['pounded-yam', 'eba', 'fufu', 'semovita', 'wheat'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 60, '/images/egusi-soup.jpg'),
  ('D002', 'ogbono-soup', 'Ogbono Soup', 'Ofe Ogbono (Igbo), Miyan Goro (Hausa)',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['ogbono seeds', 'palm oil', 'assorted meat', 'leafy greens', 'crayfish', 'pepper', 'stockfish'], ARRAY['Rich', 'Thick', 'Earthy'],
   'A deeply satisfying draw soup made from ground ogbono (African mango seeds) with a distinctive thick, stretchy texture. One of the most beloved soups across all Nigerian tribes.',
   ARRAY['pounded-yam', 'eba', 'fufu', 'amala'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 50, '/images/ogbono-soup.jpg'),
  ('D003', 'ofe-onugbu', 'Bitter Leaf Soup', 'Ofe Onugbu (Igbo)',
   'Soup', 'South-East', 'Igbo',
   ARRAY['bitter leaf', 'cocoyam', 'palm oil', 'assorted meat', 'stockfish', 'crayfish', 'ofo thickener'], ARRAY['Rich', 'Slightly Bitter', 'Earthy', 'Spicy'],
   'A classic Igbo soup thickened with cocoyam paste, made with fresh bitter leaves meticulously washed to reduce bitterness. A staple Sunday meal in Igbo homes, often served at ceremonies.',
   ARRAY['pounded-yam', 'eba', 'fufu'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 75, '/images/ofe-onugbu.jpg'),
  ('D004', 'ofe-oha', 'Oha Soup', 'Ofe Oha (Igbo)',
   'Soup', 'South-East', 'Igbo',
   ARRAY['oha leaves', 'cocoyam', 'palm oil', 'assorted meat', 'crayfish', 'uziza leaves', 'ofor'], ARRAY['Mild', 'Earthy', 'Aromatic'],
   'A delicate Igbo soup made with oha (ora) leaves, thickened with cocoyam. Lighter and more aromatic than bitter leaf soup, with a distinctive flavour from the oha leaves. Considered a prestigious dish.',
   ARRAY['pounded-yam', 'eba', 'fufu'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 70, '/images/ofe-oha.jpg'),
  ('D005', 'edikang-ikong', 'Edikang Ikong Soup', 'Edikang Ikong (Efik/Ibibio)',
   'Soup', 'South-South', 'Efik / Ibibio',
   ARRAY['ugwu leaves', 'waterleaf', 'palm oil', 'assorted meat', 'periwinkle', 'stockfish', 'crayfish'], ARRAY['Rich', 'Leafy', 'Savoury'],
   'A prestigious soup from the Efik people of Cross River State, made with a generous combination of ugwu and waterleaf. Protein-rich and nutritious, it is served at important occasions and celebrations.',
   ARRAY['pounded-yam', 'eba', 'fufu', 'wheat'],
   FALSE, FALSE, TRUE,
   FALSE, TRUE,
   2, 60, '/images/edikang-ikong.jpg'),
  ('D006', 'afang-soup', 'Afang Soup', 'Afang (Efik/Ibibio)',
   'Soup', 'South-South', 'Efik / Ibibio',
   ARRAY['afang leaves', 'waterleaf', 'palm oil', 'assorted meat', 'periwinkle', 'crayfish', 'stockfish'], ARRAY['Rich', 'Slightly Bitter', 'Savoury'],
   'A rich South-South Nigerian soup made with afang (okazi) leaves and waterleaf. Distinguished by its unique slightly bitter taste from the afang leaves. A cultural staple at Efik and Ibibio celebrations.',
   ARRAY['pounded-yam', 'eba', 'fufu', 'wheat'],
   FALSE, FALSE, TRUE,
   FALSE, TRUE,
   2, 65, '/images/afang-soup.jpg'),
  ('D007', 'banga-soup', 'Banga Soup', 'Ofe Akwu (Igbo), Banga (Urhobo/Ijaw)',
   'Soup', 'South-South / South-East', 'Urhobo / Ijaw / Igbo',
   ARRAY['palm fruit', 'assorted meat', 'banga spices', 'oburunbebe stick', 'beletete', 'crayfish', 'catfish'], ARRAY['Rich', 'Aromatic', 'Spicy'],
   'A fragrant soup made directly from fresh palm fruit extract, distinct from regular palm oil soups. The Urhobo version uses special banga spices including oburunbebe that give it a unique aroma impossible to replicate.',
   ARRAY['starch', 'eba', 'pounded-yam', 'ofada-rice'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 90, '/images/banga-soup.jpg'),
  ('D008', 'efo-riro', 'Efo Riro', 'Efo Riro (Yoruba)',
   'Soup', 'South-West', 'Yoruba',
   ARRAY['shoko/spinach leaves', 'palm oil', 'assorted meat', 'locust beans', 'crayfish', 'tatashe', 'pepper'], ARRAY['Rich', 'Savoury', 'Slightly Smoky'],
   'A beloved Yoruba vegetable soup made with shoko or spinach, cooked in a rich palm oil and pepper base. The use of iru (locust beans) gives it a distinctive deep umami flavour that sets it apart.',
   ARRAY['pounded-yam', 'eba', 'amala', 'fufu'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 45, '/images/efo-riro.jpg'),
  ('D009', 'gbegiri', 'Gbegiri Soup', 'Gbegiri (Yoruba)',
   'Soup', 'South-West', 'Yoruba',
   ARRAY['beans', 'palm oil', 'assorted meat', 'crayfish', 'locust beans', 'pepper'], ARRAY['Mild', 'Creamy', 'Savoury'],
   'A smooth, golden Yoruba bean soup with a creamy consistency. It is rarely eaten alone — it is classically combined with ewedu and stew to form Abula, one of the most iconic Nigerian food combinations.',
   ARRAY['amala', 'ewedu', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   1, 50, '/images/gbegiri.jpg'),
  ('D010', 'ewedu', 'Ewedu Soup', 'Ewedu (Yoruba)',
   'Soup', 'South-West', 'Yoruba',
   ARRAY['jute leaves', 'locust beans', 'kaun (potash)', 'crayfish'], ARRAY['Mild', 'Slimy', 'Light'],
   'A light, draw soup made from jute leaves, characteristic for its smooth slimy texture. A cornerstone of Yoruba cuisine, almost always served alongside gbegiri and stew over amala in the classic combination known as Abula.',
   ARRAY['amala', 'gbegiri', 'pounded-yam'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   1, 20, '/images/ewedu.jpg'),
  ('D011', 'okra-soup', 'Okra Soup', 'Ila Alasepo (Yoruba), Ofe Ọkụrụ (Igbo)',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['okra', 'palm oil', 'assorted meat', 'crayfish', 'pepper', 'stockfish'], ARRAY['Slimy', 'Savoury', 'Mild'],
   'A versatile Nigerian soup made with chopped or blended okra, appreciated for its slimy draw texture. It can be prepared plain or enriched with ogbono, egusi, or various proteins. Every tribe has their own version.',
   ARRAY['pounded-yam', 'eba', 'fufu', 'amala'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 40, '/images/okra-soup.jpg'),
  ('D012', 'pepper-soup', 'Pepper Soup', 'Obe Ata (Yoruba), Ofe Akara (Igbo)',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['assorted meat or fish', 'pepper soup spices', 'utazi leaves', 'scent leaves', 'pepper', 'crayfish'], ARRAY['Fiery', 'Aromatic', 'Light'],
   'A fiery, aromatic broth-based soup made with a blend of Nigerian pepper soup spices. Can feature catfish, goat meat, cow foot, or chicken. Famously served at bars and as a remedy for colds. Light but intensely flavoured.',
   ARRAY['agege-bread', 'boiled-yam', 'white-rice'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   5, 45, '/images/pepper-soup.jpg'),
  ('D013', 'nsala-soup', 'White Soup', 'Ofe Nsala (Igbo)',
   'Soup', 'South-East', 'Igbo',
   ARRAY['catfish', 'yam', 'utazi leaves', 'crayfish', 'pepper', 'uziza leaves'], ARRAY['Light', 'Aromatic', 'Spicy'],
   'A delicate, light-coloured Igbo soup made without palm oil, thickened with yam. The absence of palm oil allows the fresh catfish and aromatic spices to shine. Often prepared for new mothers and the elderly.',
   ARRAY['pounded-yam', 'fufu', 'eba'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 50, '/images/nsala-soup.jpg'),
  ('D014', 'ofe-owerri', 'Ofe Owerri', 'Ofe Owerri (Igbo)',
   'Soup', 'South-East', 'Igbo (Owerri)',
   ARRAY['cocoyam', 'palm oil', 'ede (cocoyam)', 'uziza leaves', 'assorted meat', 'stockfish', 'crayfish', 'oha leaves'], ARRAY['Rich', 'Thick', 'Aromatic'],
   'A rich, prestigious Igbo soup from the Owerri region, distinguished by its thick cocoyam base and combination of uziza and oha leaves. Often described as the ''queen of Igbo soups'' — served at major ceremonies.',
   ARRAY['pounded-yam', 'fufu', 'eba'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 80, '/images/ofe-owerri.jpg'),
  ('D015', 'miyan-kuka', 'Baobab Leaf Soup', 'Miyan Kuka (Hausa)',
   'Soup', 'North', 'Hausa / Fulani',
   ARRAY['baobab leaves (kuka)', 'dawadawa', 'palm oil', 'meat', 'dried fish', 'pepper'], ARRAY['Earthy', 'Slightly Sour', 'Light'],
   'A traditional Northern Nigerian soup made from dried, powdered baobab leaves with a characteristic earthy, slightly sour taste. A staple in Hausa and Fulani cuisine, typically eaten daily in Northern homes.',
   ARRAY['tuwo-shinkafa', 'tuwo-masara'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 30, '/images/miyan-kuka.jpg'),
  ('D016', 'miyan-taushe', 'Pumpkin Soup', 'Miyan Taushe (Hausa)',
   'Soup', 'North', 'Hausa',
   ARRAY['pumpkin', 'groundnut paste', 'meat', 'dried fish', 'dawadawa', 'pepper'], ARRAY['Mild', 'Sweet', 'Creamy'],
   'A rich Northern Nigerian soup made with pumpkin and groundnut paste, giving it a creamy, mildly sweet flavour. A beloved comfort food in Hausa households, especially during the harvest season.',
   ARRAY['tuwo-shinkafa', 'tuwo-masara'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 40, '/images/miyan-taushe.jpg'),
  ('D017', 'waterleaf-soup', 'Waterleaf Soup', 'Gbure (Yoruba), Mgbolodi (Igbo)',
   'Soup', 'South-West / South-East', 'Yoruba / Igbo',
   ARRAY['waterleaf', 'palm oil', 'crayfish', 'assorted meat', 'pepper'], ARRAY['Light', 'Mild', 'Fresh'],
   'A light, nutritious soup made from waterleaf, one of Nigeria''s most readily available greens. Quick to prepare and high in vitamins, it is a common everyday meal across Southern Nigeria.',
   ARRAY['eba', 'pounded-yam', 'fufu'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 30, '/images/waterleaf-soup.jpg'),
  ('D018', 'fisherman-soup', 'Fisherman Soup', 'Efere Imoibe (Ijaw)',
   'Soup', 'South-South', 'Ijaw / Niger Delta',
   ARRAY['fresh fish', 'crayfish', 'periwinkle', 'palm oil', 'fresh pepper', 'scent leaves', 'uziza'], ARRAY['Spicy', 'Smoky', 'Rich', 'Aromatic'],
   'A deeply flavourful Delta soup loaded with fresh fish, periwinkle, and crayfish. Born from the Niger Delta''s riverine communities, it celebrates the abundant seafood of the region. Bold, smoky, and intensely aromatic.',
   ARRAY['starch', 'eba', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, TRUE,
   4, 55, '/images/fisherman-soup.jpg'),
  ('D019', 'abak-atama', 'Abak Atama Soup', 'Abak Atama (Efik)',
   'Soup', 'South-South', 'Efik',
   ARRAY['palm fruit', 'atama leaves', 'periwinkle', 'assorted meat', 'crayfish', 'stockfish'], ARRAY['Rich', 'Aromatic', 'Spicy'],
   'A distinctive Efik soup made from palm fruit and the unique atama leaf which gives it an unmistakeable aroma no other Nigerian soup has. A centrepiece at Efik traditional events and celebrations.',
   ARRAY['starch', 'eba', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, TRUE,
   3, 90, '/images/abak-atama.jpg'),
  ('D020', 'tom-brown-soup', 'Groundnut Soup', 'Miyan Gyada (Hausa), Ofe Ahụ (Igbo)',
   'Soup', 'North / Nationwide', 'Hausa / Pan-Nigerian',
   ARRAY['groundnut paste', 'assorted meat', 'tomato', 'pepper', 'onion', 'seasoning'], ARRAY['Rich', 'Nutty', 'Mild'],
   'A hearty soup made from roasted groundnut paste, producing a thick, richly flavoured broth. Popular across Nigeria but a staple in the North where groundnuts are abundantly grown.',
   ARRAY['tuwo-shinkafa', 'white-rice', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 55, '/images/groundnut-soup.jpg'),
  ('D021', 'pounded-yam', 'Pounded Yam', 'Iyan (Yoruba), Ji Ikpakala (Igbo)',
   'Swallow', 'Nationwide', 'Pan-Nigerian',
   ARRAY['yam'], ARRAY['Neutral', 'Starchy', 'Smooth'],
   'Nigeria''s most prestigious swallow, made from boiled yam pounded in a mortar until smooth and stretchy. It has a superior texture to instant alternatives and is the preferred swallow at ceremonies and celebrations.',
   ARRAY['egusi-soup', 'ofe-onugbu', 'ofe-oha', 'edikang-ikong', 'ogbono-soup'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 45, '/images/pounded-yam.jpg'),
  ('D022', 'eba', 'Eba (Garri Swallow)', 'Eba (Nationwide)',
   'Swallow', 'Nationwide', 'Pan-Nigerian',
   ARRAY['garri (cassava flour)', 'hot water'], ARRAY['Neutral', 'Slightly Sour', 'Dense'],
   'Nigeria''s most widely eaten swallow, made by mixing garri with hot water. Affordable, quick to prepare, and available everywhere. The everyday staple in millions of Nigerian homes across all social classes.',
   ARRAY['egusi-soup', 'ogbono-soup', 'ofe-onugbu', 'efo-riro', 'okra-soup'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 5, '/images/eba.jpg'),
  ('D023', 'amala', 'Amala', 'Amala (Yoruba)',
   'Swallow', 'South-West', 'Yoruba',
   ARRAY['yam flour (elubo)'], ARRAY['Earthy', 'Slightly Bitter', 'Smooth'],
   'A dark brown Yoruba swallow made from dried yam flour, with a distinctive earthy taste and velvety smooth texture. Inseparable from gbegiri and ewedu in the famous Abula combination. A Yoruba cultural icon.',
   ARRAY['gbegiri', 'ewedu', 'efo-riro', 'okra-soup'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 15, '/images/amala.jpg'),
  ('D024', 'fufu', 'Fufu', 'Akpu (Igbo), Fufu (Nationwide)',
   'Swallow', 'Nationwide', 'Pan-Nigerian',
   ARRAY['fermented cassava'], ARRAY['Sour', 'Dense', 'Starchy'],
   'A fermented cassava swallow with a characteristic sour smell and dense, stretchy texture. A strong cultural preference in Igbo and South-South households. Its unique fermented tang is considered essential by its devotees.',
   ARRAY['ofe-onugbu', 'ofe-oha', 'ogbono-soup', 'egusi-soup'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 30, '/images/fufu.jpg'),
  ('D025', 'semovita', 'Semovita', 'Semo (Nationwide)',
   'Swallow', 'Nationwide', 'Pan-Nigerian',
   ARRAY['semolina'], ARRAY['Neutral', 'Soft', 'Light'],
   'A light, white semolina-based swallow that is milder in taste and texture than pounded yam. Widely available and easy to prepare, it is the preferred swallow in many urban households and restaurants.',
   ARRAY['egusi-soup', 'edikang-ikong', 'ofe-oha', 'ogbono-soup'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 10, '/images/semovita.jpg'),
  ('D026', 'wheat-swallow', 'Wheat Swallow', 'Wheat (Nationwide)',
   'Swallow', 'Nationwide', 'Pan-Nigerian',
   ARRAY['whole wheat flour'], ARRAY['Neutral', 'Slightly Nutty', 'Dense'],
   'A healthier swallow option made from whole wheat flour, darker in colour than semo and heavier in texture. Preferred by health-conscious Nigerians as a higher-fibre alternative to other swallows.',
   ARRAY['egusi-soup', 'edikang-ikong', 'efo-riro', 'ofe-oha'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 10, '/images/wheat-swallow.jpg'),
  ('D027', 'tuwo-shinkafa', 'Tuwo Shinkafa', 'Tuwo Shinkafa (Hausa)',
   'Swallow', 'North', 'Hausa / Fulani',
   ARRAY['soft rice'], ARRAY['Neutral', 'Soft', 'Mild'],
   'A Northern Nigerian swallow made from soft, overcooked rice mashed into a smooth, moldable form. The preferred swallow in Hausa cuisine, it is gentler in texture than other swallows and pairs perfectly with Northern soups.',
   ARRAY['miyan-kuka', 'miyan-taushe', 'groundnut-soup'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 40, '/images/tuwo-shinkafa.jpg'),
  ('D028', 'tuwo-masara', 'Tuwo Masara', 'Tuwo Masara (Hausa)',
   'Swallow', 'North', 'Hausa',
   ARRAY['corn flour'], ARRAY['Neutral', 'Starchy', 'Dense'],
   'A corn-based Northern Nigerian swallow, slightly rougher in texture than tuwo shinkafa but equally filling. A daily staple in many Northern households, especially in rural areas where corn is widely cultivated.',
   ARRAY['miyan-kuka', 'miyan-taushe'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 30, '/images/tuwo-masara.jpg'),
  ('D029', 'jollof-rice', 'Jollof Rice', 'Riz Jollof (Nationwide)',
   'Rice Dish', 'Nationwide', 'Pan-Nigerian',
   ARRAY['long grain rice', 'tomato', 'tatashe', 'onion', 'palm oil', 'chicken stock', 'bay leaves'], ARRAY['Smoky', 'Savoury', 'Rich'],
   'Nigeria''s most famous dish and its greatest cultural export. Rice cooked in a rich tomato and pepper base until it achieves the coveted smoky bottom layer called ''party jollof''. A staple at every Nigerian celebration.',
   ARRAY['fried-chicken', 'moi-moi', 'coleslaw', 'plantain'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   2, 60, '/images/jollof-rice.jpg'),
  ('D030', 'ofada-rice', 'Ofada Rice and Ayamase', 'Ofada (Yoruba)',
   'Rice Dish', 'South-West', 'Yoruba',
   ARRAY['ofada rice (local parboiled rice)', 'green pepper', 'tatashe', 'palm oil', 'assorted meat', 'locust beans'], ARRAY['Smoky', 'Spicy', 'Earthy', 'Rich'],
   'A celebrated Yoruba dish of local unpolished ofada rice served with ayamase — a pungent, spicy green pepper stew. Wrapped in banana leaf when served traditionally. The intense flavour of the stew is unforgettable.',
   ARRAY['ayamase-stew', 'fried-plantain'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   4, 50, '/images/ofada-rice.jpg'),
  ('D031', 'coconut-rice', 'Coconut Rice', 'Eba Agbon (Yoruba)',
   'Rice Dish', 'South-West / South-South', 'Yoruba / Coastal communities',
   ARRAY['rice', 'coconut milk', 'coconut flesh', 'assorted seafood', 'pepper', 'onion'], ARRAY['Sweet', 'Creamy', 'Mild'],
   'A fragrant, mildly sweet rice dish cooked in fresh coconut milk, popular along Nigeria''s coastal communities. The natural sweetness of the coconut pairs beautifully with seafood, making it a unique and beloved dish.',
   ARRAY['fried-fish', 'chicken', 'plantain'],
   FALSE, FALSE, TRUE,
   FALSE, TRUE,
   1, 45, '/images/coconut-rice.jpg'),
  ('D032', 'fried-rice', 'Nigerian Fried Rice', 'Fried Rice (Nationwide)',
   'Rice Dish', 'Nationwide', 'Pan-Nigerian',
   ARRAY['parboiled rice', 'mixed vegetables', 'liver', 'green onion', 'curry powder', 'thyme', 'butter'], ARRAY['Savoury', 'Mild', 'Herby'],
   'Nigerian fried rice stands apart from other versions — cooked with mixed vegetables, seasoned with curry and thyme, and typically enriched with diced liver. A party staple served alongside jollof rice at every Nigerian celebration.',
   ARRAY['chicken', 'moi-moi', 'coleslaw', 'plantain'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   1, 45, '/images/fried-rice.jpg'),
  ('D033', 'concoction-rice', 'Concoction Rice', 'Native Rice / Iwuk Edesi (Efik)',
   'Rice Dish', 'Nationwide', 'Pan-Nigerian',
   ARRAY['rice', 'palm oil', 'stockfish', 'crayfish', 'pepper', 'onion'], ARRAY['Rich', 'Smoky', 'Earthy'],
   'A rustic, deeply flavoured one-pot rice dish cooked with palm oil and assorted meats. Each cook''s version is different — no two pots taste the same. The name captures its freestyle, throw-it-all-in character.',
   ARRAY['fried-fish', 'chicken', 'moi-moi'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 50, '/images/concoction-rice.jpg'),
  ('D034', 'suya', 'Suya', 'Suya (Hausa)',
   'Grilled & BBQ', 'North / Nationwide', 'Hausa / Fulani',
   ARRAY['beef', 'suya spice (yaji)', 'groundnut powder', 'ginger', 'paprika', 'onion'], ARRAY['Spicy', 'Smoky', 'Nutty'],
   'Thinly sliced beef skewers marinated in yaji — a complex spice blend of groundnut powder, ginger, and paprika — then grilled over an open flame. A Nigerian night-out institution. Served with sliced onions and tomatoes.',
   ARRAY['sliced-onions', 'tomatoes', 'agege-bread'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   4, 30, '/images/suya.jpg'),
  ('D035', 'asun', 'Asun', 'Asun (Yoruba)',
   'Grilled & BBQ', 'South-West', 'Yoruba',
   ARRAY['goat meat', 'scotch bonnet pepper', 'onion', 'seasoning', 'bell pepper'], ARRAY['Fiery', 'Smoky', 'Juicy'],
   'Smoky, spicy grilled goat meat cut into small pieces and tossed in a fiery pepper sauce. A beloved party small chop and bar snack that exemplifies the bold, unapologetic flavours of Yoruba cuisine.',
   ARRAY['beer', 'soft-drinks'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   5, 35, '/images/asun.jpg'),
  ('D036', 'isi-ewu', 'Spiced Goat Head', 'Isi Ewu (Igbo)',
   'Grilled & BBQ', 'South-East', 'Igbo',
   ARRAY['goat head', 'utazi leaves', 'palm oil', 'crayfish', 'ehuru', 'ogiri'], ARRAY['Rich', 'Spicy', 'Gamey', 'Aromatic'],
   'A bold Igbo delicacy of spiced and roasted goat head, served in a rich palm oil sauce with utazi leaves. A staple at Igbo bars and restaurants, eaten communally. The utazi leaves cut through the richness beautifully.',
   ARRAY['palm-wine', 'beer'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   4, 120, '/images/isi-ewu.jpg'),
  ('D037', 'nkwobi', 'Spiced Cow Foot', 'Nkwobi (Igbo)',
   'Grilled & BBQ', 'South-East', 'Igbo',
   ARRAY['cow foot', 'palm oil', 'utazi leaves', 'ehuru', 'ogiri', 'crayfish'], ARRAY['Rich', 'Spicy', 'Gelatinous', 'Aromatic'],
   'A rich Igbo speciality of cow foot cooked in a spiced palm oil sauce until the collagen renders into a thick, gelatinous coating. Garnished with fresh utazi leaves. A classic accompaniment to palm wine.',
   ARRAY['palm-wine', 'beer'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 150, '/images/nkwobi.jpg'),
  ('D038', 'kilishi', 'Kilishi', 'Kilishi (Hausa)',
   'Grilled & BBQ', 'North', 'Hausa',
   ARRAY['beef', 'groundnut paste', 'suya spice', 'tomato paste', 'ginger', 'garlic'], ARRAY['Spicy', 'Smoky', 'Chewy', 'Nutty'],
   'Northern Nigeria''s answer to beef jerky — thin sheets of beef marinated in a groundnut paste and spice coating, then sun-dried and grilled. Intensely flavoured, extremely portable, and a beloved Northern snack and gift.',
   ARRAY['kunu', 'soft-drinks'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   4, 480, '/images/kilishi.jpg'),
  ('D039', 'bole', 'Bole (Roasted Plantain)', 'Bole (Rivers/Delta), Boli (Yoruba)',
   'Street Food', 'South-South / South-West', 'Rivers / Yoruba',
   ARRAY['plantain', 'palm oil sauce', 'roasted fish', 'pepper sauce'], ARRAY['Smoky', 'Sweet-Savoury', 'Rich'],
   'Whole plantains roasted directly over an open fire until caramelised, served with a spiced palm oil sauce and roasted fish. A beloved Port Harcourt street food and a late-night staple across Southern Nigeria.',
   ARRAY['roasted-fish', 'pepper-sauce'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 25, '/images/bole.jpg'),
  ('D040', 'akara', 'Akara (Bean Cakes)', 'Akara (Yoruba), Kosai (Hausa)',
   'Breakfast', 'Nationwide', 'Pan-Nigerian',
   ARRAY['black-eyed beans', 'onion', 'scotch bonnet pepper', 'palm oil (for frying)'], ARRAY['Savoury', 'Crispy', 'Mild'],
   'Deep-fried bean cakes made from blended black-eyed beans. Crispy on the outside, soft and airy inside. Nigeria''s most beloved breakfast street food, sold every morning by roadside vendors across the country.',
   ARRAY['ogi', 'pap', 'agege-bread'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   2, 30, '/images/akara.jpg'),
  ('D041', 'moi-moi', 'Moi Moi (Steamed Bean Pudding)', 'Moi Moi (Nationwide), Ofuloju (Igbo)',
   'Snack', 'Nationwide', 'Pan-Nigerian',
   ARRAY['black-eyed beans', 'tatashe', 'scotch bonnet', 'onion', 'egg', 'fish', 'crayfish'], ARRAY['Savoury', 'Soft', 'Rich'],
   'Steamed bean pudding made from blended beans, peppers, and various fillings including boiled egg, fish, and crayfish. A Nigerian party staple alongside jollof rice. Infinitely versatile — every cook has their own version.',
   ARRAY['jollof-rice', 'ogi', 'agege-bread'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 60, '/images/moi-moi.jpg'),
  ('D042', 'abacha', 'Abacha (African Salad)', 'Abacha (Igbo)',
   'Snack', 'South-East', 'Igbo',
   ARRAY['dried shredded cassava', 'ugba', 'palm oil', 'potash', 'crayfish', 'utazi leaves', 'garden eggs'], ARRAY['Tangy', 'Spicy', 'Rich'],
   'A cold Igbo salad made from shredded dried cassava, mixed with ugba (fermented oil bean), palm oil emulsified with potash, and fresh utazi leaves. A unique Nigerian dish — no heat required, just mixing and layering.',
   ARRAY['palm-wine', 'beer'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   3, 20, '/images/abacha.jpg'),
  ('D043', 'puff-puff', 'Puff Puff', 'Puff Puff (Nationwide), Bofrot',
   'Snack', 'Nationwide', 'Pan-Nigerian',
   ARRAY['flour', 'yeast', 'sugar', 'nutmeg', 'water', 'oil (for frying)'], ARRAY['Sweet', 'Fluffy', 'Soft'],
   'Deep-fried dough balls, golden on the outside and pillowy inside. A universal Nigerian party snack and small chop staple. The slight nutmeg flavour is the signature touch. Simple, irresistible, universally loved.',
   ARRAY['pepper-sauce', 'soft-drinks'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 40, '/images/puff-puff.jpg'),
  ('D044', 'chin-chin', 'Chin Chin', 'Chin Chin (Nationwide)',
   'Snack', 'Nationwide', 'Pan-Nigerian',
   ARRAY['flour', 'sugar', 'butter', 'egg', 'milk', 'nutmeg'], ARRAY['Sweet', 'Crunchy', 'Buttery'],
   'Crunchy deep-fried pastry snacks made from flour dough flavoured with nutmeg. Can be made soft or extra-crunchy depending on preparation. A Christmas and celebration staple, packaged and gifted across Nigeria.',
   ARRAY['soft-drinks', 'zobo'],
   FALSE, TRUE, TRUE,
   FALSE, FALSE,
   0, 60, '/images/chin-chin.jpg'),
  ('D045', 'roasted-corn', 'Roasted Corn and Ube', 'Agbado (Yoruba), Oka Oku (Igbo)',
   'Street Food', 'Nationwide', 'Pan-Nigerian',
   ARRAY['fresh corn on cob', 'african pear (ube)'], ARRAY['Smoky', 'Sweet', 'Earthy'],
   'Corn roasted directly over charcoal and served with softened ube (African pear). An iconic Nigerian street food combination — the charred corn and buttery ube are inseparable. A rainy season staple across the country.',
   ARRAY['ube'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 20, '/images/roasted-corn.jpg'),
  ('D046', 'ogi', 'Ogi (Pap / Akamu)', 'Ogi (Yoruba), Akamu (Igbo), Kunu Gyada (Hausa)',
   'Breakfast', 'Nationwide', 'Pan-Nigerian',
   ARRAY['fermented corn', 'water'], ARRAY['Sour', 'Smooth', 'Light'],
   'A smooth, porridge-like breakfast drink made from fermented corn. Served hot or cold, sweetened with sugar, or paired with akara or moi moi. A weaning food, a comfort food, and a hangover remedy across Nigeria.',
   ARRAY['akara', 'moi-moi', 'agege-bread'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 15, '/images/ogi.jpg'),
  ('D047', 'agege-bread', 'Agege Bread', 'Agege Bread (Nationwide)',
   'Breakfast', 'South-West / Nationwide', 'Pan-Nigerian',
   ARRAY['flour', 'yeast', 'sugar', 'butter', 'milk'], ARRAY['Sweet', 'Soft', 'Fluffy'],
   'Nigeria''s most beloved soft bread, originating from Agege in Lagos. Its signature dense, pillowy texture and slightly sweet taste make it perfect with tea, ogi, or butter. Sold in every neighbourhood across Nigeria.',
   ARRAY['ogi', 'tea', 'akara', 'beans'],
   FALSE, TRUE, TRUE,
   FALSE, FALSE,
   0, 90, '/images/agege-bread.jpg'),
  ('D048', 'zobo', 'Zobo Drink', 'Zobo (Hausa), Sobo (Yoruba)',
   'Drink', 'Nationwide', 'Pan-Nigerian',
   ARRAY['dried hibiscus petals', 'ginger', 'cloves', 'pineapple', 'sugar'], ARRAY['Tart', 'Floral', 'Refreshing'],
   'A vibrant red drink made from steeped dried hibiscus petals, infused with ginger, cloves, and fresh fruit. Nigeria''s most popular homemade drink — present at every party, owambe, and celebration. Deeply refreshing when chilled.',
   ARRAY['chin-chin', 'puff-puff', 'small-chops'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 30, '/images/zobo.jpg'),
  ('D049', 'kunu', 'Kunu', 'Kunu Zaki (Hausa)',
   'Drink', 'North / Nationwide', 'Hausa',
   ARRAY['millet or sorghum', 'ginger', 'cloves', 'sugar'], ARRAY['Creamy', 'Spiced', 'Mildly Sweet'],
   'A creamy, mildly spiced grain-based drink made from fermented millet or sorghum. Thick, filling, and naturally probiotic. Originally from the North, it is now sold by street vendors across the entire country.',
   ARRAY['kilishi', 'masa'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   1, 60, '/images/kunu.jpg'),
  ('D050', 'palm-wine', 'Palm Wine', 'Oguro (Yoruba), Nkwu Onu (Igbo), Tuwon Rafi (Hausa)',
   'Drink', 'Nationwide', 'Pan-Nigerian',
   ARRAY['palm tree sap'], ARRAY['Sweet', 'Slightly Fermented', 'Yeasty'],
   'Freshly tapped palm sap that ferments naturally into a mildly alcoholic, bubbly drink. Sweet when fresh, increasingly fermented as hours pass. A central part of Nigerian ceremonies, especially in Igbo and Yoruba culture.',
   ARRAY['nkwobi', 'isi-ewu', 'abacha', 'kilishi'],
   TRUE, TRUE, FALSE,
   FALSE, FALSE,
   0, 0, '/images/palm-wine.jpg'),
  ('D051', 'tiger-nut-milk', 'Tiger Nut Milk', 'Kunun Aya (Hausa), Ofio (Yoruba)',
   'Drink', 'North / Nationwide', 'Hausa / Pan-Nigerian',
   ARRAY['tiger nuts', 'dates', 'coconut', 'water'], ARRAY['Sweet', 'Creamy', 'Nutty'],
   'A naturally sweet, dairy-free milk made from soaked and blended tiger nuts. One of Nigeria''s most nutritious traditional drinks — high in fibre and natural sugars. Known for its smooth, almost dessert-like sweetness.',
   ARRAY['chin-chin', 'masa'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 20, '/images/tiger-nut-milk.jpg'),
  ('D052', 'fura-da-nono', 'Fura da Nono', 'Fura da Nono (Fulani/Hausa)',
   'Drink', 'North', 'Fulani / Hausa',
   ARRAY['millet balls (fura)', 'fermented cow milk (nono)', 'ginger', 'cloves'], ARRAY['Sour', 'Creamy', 'Spiced'],
   'A traditional Fulani drink of spiced millet balls dissolved into fermented cow milk. Thick, tangy, filling, and deeply nutritious. The signature drink of Fulani herdsmen and one of Northern Nigeria''s most culturally significant foods.',
   ARRAY[]::TEXT[],
   FALSE, TRUE, TRUE,
   FALSE, FALSE,
   1, 30, '/images/fura-da-nono.jpg'),
  ('D053', 'masa', 'Masa (Rice Cakes)', 'Masa (Hausa)',
   'Breakfast', 'North', 'Hausa',
   ARRAY['rice', 'sugar', 'yeast', 'oil'], ARRAY['Mild', 'Slightly Sweet', 'Spongy'],
   'Soft, spongy rice cakes cooked in special moulded pans, common in Northern Nigeria. Eaten for breakfast with honey, groundnut soup, or kunu. The airy, lightly fermented texture makes them highly addictive.',
   ARRAY['kunu', 'honey', 'groundnut-soup'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 40, '/images/masa.jpg'),
  ('D054', 'bean-porridge', 'Bean Porridge', 'Ewa Agoyin (Yoruba), Moin Moin Ewa',
   'Breakfast', 'South-West', 'Yoruba',
   ARRAY['beans', 'palm oil', 'tatashe', 'onion', 'crayfish'], ARRAY['Rich', 'Savoury', 'Earthy'],
   'Soft-cooked beans served with a rich, dark palm oil and pepper sauce. Ewa Agoyin — the specific Lagos street version — features an especially spicy, smoky sauce that is its defining characteristic. Eaten at any time of day.',
   ARRAY['agege-bread', 'ogi', 'plantain'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   3, 60, '/images/bean-porridge.jpg'),
  ('D055', 'yam-porridge', 'Yam Porridge (Asaro)', 'Asaro (Yoruba), Ji Mmiri Oku (Igbo)',
   'Breakfast', 'Nationwide', 'Pan-Nigerian',
   ARRAY['yam', 'palm oil', 'tomato', 'pepper', 'crayfish', 'onion'], ARRAY['Rich', 'Savoury', 'Starchy'],
   'Yam cooked in a spiced palm oil base until soft and slightly broken down, absorbing all the flavours of the stew. A deeply comforting dish, often made when someone is ill or on a cold day. A universal Nigerian comfort food.',
   ARRAY['fried-fish', 'chicken'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   2, 40, '/images/yam-porridge.jpg'),
  ('D056', 'nkatie', 'Roasted Groundnuts', 'Ekpa Oji (Igbo), Epa (Yoruba), Gyada (Hausa)',
   'Snack', 'Nationwide', 'Pan-Nigerian',
   ARRAY['groundnuts', 'salt'], ARRAY['Nutty', 'Salty', 'Crunchy'],
   'Dry-roasted groundnuts, lightly salted and sold in small packets by roadside vendors. Nigeria''s most ubiquitous snack — found at bus stops, markets, and traffic lights across the entire country at any hour.',
   ARRAY['garri', 'zobo', 'soft-drinks'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 20, '/images/groundnuts.jpg'),
  ('D057', 'kuli-kuli', 'Kuli Kuli', 'Kuli Kuli (Hausa)',
   'Snack', 'North / Nationwide', 'Hausa',
   ARRAY['groundnut paste', 'salt', 'pepper', 'oil'], ARRAY['Nutty', 'Crunchy', 'Salty', 'Spicy'],
   'A crunchy Northern Nigerian snack made from defatted groundnut paste, shaped into rings or sticks and deep-fried until hard. Intensely nutty with a hint of spice. Eaten alone as a snack or crumbled into garri water.',
   ARRAY['garri', 'zobo', 'kunu'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   2, 60, '/images/kuli-kuli.jpg'),
  ('D058', 'fried-plantain', 'Fried Plantain (Dodo)', 'Dodo (Yoruba), Ojukwu (Igbo)',
   'Snack', 'Nationwide', 'Pan-Nigerian',
   ARRAY['ripe plantain', 'oil'], ARRAY['Sweet', 'Caramelised', 'Soft'],
   'Sliced ripe plantain deep-fried in oil until golden and caramelised. A non-negotiable accompaniment at Nigerian parties alongside jollof rice. The riper the plantain, the sweeter and more indulgent the result.',
   ARRAY['jollof-rice', 'fried-rice', 'beans', 'eggs'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 15, '/images/fried-plantain.jpg'),
  ('D059', 'ugba', 'Ugba (Oil Bean Salad)', 'Ugba (Igbo), Ukpaka',
   'Snack', 'South-East', 'Igbo',
   ARRAY['fermented oil bean', 'utazi leaves', 'palm oil', 'crayfish', 'pepper', 'potash'], ARRAY['Pungent', 'Rich', 'Tangy'],
   'A fermented oil bean salad with a strong, distinctive fermented aroma that Igbo people regard as deeply comforting. Mixed with palm oil and utazi leaves, it is eaten as a snack or added to abacha. An acquired taste with devoted fans.',
   ARRAY['abacha', 'palm-wine'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   2, 15, '/images/ugba.jpg'),
  ('D060', 'starch-banga', 'Starch and Banga', 'Starch (Delta/Urhobo)',
   'Swallow', 'South-South', 'Urhobo / Ijaw',
   ARRAY['cassava starch'], ARRAY['Neutral', 'Gelatinous', 'Smooth'],
   'A clear, gelatinous Delta swallow made from cassava starch with a uniquely smooth, almost translucent appearance. The perfect partner for banga soup — the two are considered inseparable in Delta cuisine.',
   ARRAY['banga-soup', 'fisherman-soup'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 20, '/images/starch.jpg'),
  ('D061', 'abula', 'Abula', 'Abula (Yoruba)',
   'Soup', 'South-West', 'Yoruba',
   ARRAY['gbegiri', 'ewedu', 'stew', 'amala'], ARRAY['Rich', 'Earthy', 'Complex', 'Savoury'],
   'Not a single dish but the iconic Yoruba combination: amala swallow served with a trio of gbegiri, ewedu, and stew poured together in layers. Greater than the sum of its parts — the definitive Yoruba meal experience.',
   ARRAY['amala'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 90, '/images/abula.jpg'),
  ('D062', 'egusi-eba-combo', 'Egusi and Eba Combination', 'Egusi na Eba (Nationwide)',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['egusi', 'eba'], ARRAY['Rich', 'Earthy', 'Satisfying'],
   'The most ordered combination in Nigerian restaurants — a bowl of egusi soup with eba. This pairing is the baseline against which all other Nigerian meals are measured. Simple, filling, and completely satisfying.',
   ARRAY['egusi-soup', 'eba'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 65, '/images/egusi-eba.jpg'),
  ('D063', 'nkwobi-palm-wine', 'Nkwobi and Palm Wine', 'Nkwobi na Nkwu (Igbo)',
   'Snack', 'South-East', 'Igbo',
   ARRAY['nkwobi', 'palm wine'], ARRAY['Rich', 'Spicy', 'Fermented'],
   'The classic Igbo bar combination — a plate of nkwobi and a calabash of fresh palm wine. The richness of the cow foot perfectly offsets the tartness of the wine. An experience central to Igbo socialising culture.',
   ARRAY['nkwobi', 'palm-wine'],
   FALSE, FALSE, FALSE,
   FALSE, FALSE,
   3, 150, '/images/nkwobi-palm-wine.jpg'),
  ('D064', 'ofe-akwu', 'Ofe Akwu (Palm Fruit Soup)', 'Ofe Akwu (Igbo)',
   'Soup', 'South-East', 'Igbo',
   ARRAY['palm fruit', 'assorted meat', 'stockfish', 'crayfish', 'pepper', 'uziza leaves'], ARRAY['Rich', 'Aromatic', 'Spicy'],
   'The Igbo version of palm fruit soup, made directly from freshly pounded palm fruit. Richer and more aromatic than regular palm oil soups, it carries the full fragrance of fresh palm fruit in every spoonful.',
   ARRAY['white-rice', 'eba', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 80, '/images/ofe-akwu.jpg'),
  ('D065', 'catfish-pepper-soup', 'Catfish Pepper Soup', 'Point and Kill',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['catfish', 'pepper soup spices', 'utazi leaves', 'scent leaves', 'scotch bonnet', 'onion'], ARRAY['Fiery', 'Aromatic', 'Light'],
   'The most popular version of Nigerian pepper soup — made with fresh catfish cooked in an intensely spiced broth. Called ''point and kill'' at restaurants where you select your live fish. A bar staple and cold remedy in one.',
   ARRAY['agege-bread', 'boiled-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   5, 35, '/images/catfish-pepper-soup.jpg'),
  ('D066', 'snail-pepper-soup', 'Snail Pepper Soup', 'Eju Nsi (Igbo), Ìgbín (Yoruba)',
   'Soup', 'South-East / South-West', 'Igbo / Yoruba',
   ARRAY['giant African snail', 'pepper soup spices', 'utazi', 'crayfish', 'scotch bonnet'], ARRAY['Chewy', 'Fiery', 'Aromatic'],
   'A luxurious pepper soup made with giant African snails — considered a delicacy across Southern Nigeria. The snail''s unique chewy texture absorbs the spiced broth magnificently. Often the most expensive item on any restaurant''s menu.',
   ARRAY['beer', 'palm-wine'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   4, 60, '/images/snail-pepper-soup.jpg'),
  ('D067', 'cow-leg-pepper-soup', 'Cow Leg Pepper Soup', 'Bokoto Pepper Soup',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['cow leg (bokoto)', 'pepper soup spices', 'onion', 'scotch bonnet', 'scent leaves'], ARRAY['Gelatinous', 'Fiery', 'Rich'],
   'A rich pepper soup made with cow leg — beloved for the collagen-rich broth that results from the slow cooking. The gelatinous texture of the meat and the fiery broth make it an intensely satisfying and warming dish.',
   ARRAY['beer', 'agege-bread'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   4, 120, '/images/cow-leg-pepper-soup.jpg'),
  ('D068', 'ofada-ayamase', 'Ayamase Stew', 'Ayamase (Yoruba), Ofada Stew',
   'Soup', 'South-West', 'Yoruba',
   ARRAY['green pepper', 'tatashe', 'palm oil', 'assorted meat', 'locust beans', 'onion'], ARRAY['Pungent', 'Spicy', 'Smoky', 'Rich'],
   'A pungent, intensely flavoured green pepper stew made with bleached palm oil. The combination of the green peppers and locust beans creates a complex, smoky flavour. Classically served with ofada rice wrapped in banana leaf.',
   ARRAY['ofada-rice', 'white-rice'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   5, 60, '/images/ayamase.jpg'),
  ('D069', 'draw-soup', 'Draw Soup', 'Ila Alasepo (Yoruba)',
   'Soup', 'South-West', 'Yoruba',
   ARRAY['okra', 'ogbono', 'palm oil', 'assorted meat', 'crayfish', 'locust beans'], ARRAY['Slimy', 'Rich', 'Savoury'],
   'A Yoruba combination soup blending okra and ogbono together for maximum draw and slimy texture. The combination of both thickeners creates a soup that clings perfectly to swallows. A favourite among those who love draw soups.',
   ARRAY['amala', 'pounded-yam', 'eba'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 45, '/images/draw-soup.jpg'),
  ('D070', 'boiled-yam-egg', 'Boiled Yam and Egg Sauce', 'Ji na Anu Ezi (Igbo)',
   'Breakfast', 'Nationwide', 'Pan-Nigerian',
   ARRAY['yam', 'eggs', 'tomato', 'onion', 'scotch bonnet', 'oil'], ARRAY['Savoury', 'Simple', 'Filling'],
   'Boiled yam served with a simple but satisfying fried egg sauce. One of Nigeria''s most common household breakfast combinations. Quick, filling, and infinitely adjustable based on what is in the kitchen.',
   ARRAY['fried-egg', 'tomato-sauce'],
   FALSE, TRUE, TRUE,
   FALSE, FALSE,
   2, 30, '/images/boiled-yam-egg.jpg'),
  ('D071', 'dundun', 'Dundun (Fried Yam)', 'Dundun (Yoruba)',
   'Street Food', 'South-West', 'Yoruba',
   ARRAY['yam', 'oil', 'pepper sauce'], ARRAY['Crispy', 'Starchy', 'Savoury'],
   'Sliced yam deep-fried until golden and slightly crispy on the outside. Sold by street vendors across Yorubaland, typically with a spicy pepper sauce and fried akara. A beloved afternoon snack and quick roadside meal.',
   ARRAY['akara', 'pepper-sauce'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   1, 25, '/images/dundun.jpg'),
  ('D072', 'banga-rice', 'Banga Rice', 'Ofe Akwu Rice (Delta)',
   'Rice Dish', 'South-South', 'Urhobo / Delta',
   ARRAY['rice', 'palm fruit', 'banga spices', 'assorted meat', 'crayfish'], ARRAY['Rich', 'Aromatic', 'Spicy'],
   'Rice cooked directly in fresh palm fruit extract, absorbing all the fragrance and richness of banga. A Delta speciality that is uniquely aromatic — the rice carries a deep orange colour and the unmistakeable scent of banga spices.',
   ARRAY['fried-fish', 'chicken'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 70, '/images/banga-rice.jpg'),
  ('D073', 'pepper-chicken', 'Nigerian Pepper Chicken', 'Chicken Suya / Peppered Chicken',
   'Grilled & BBQ', 'Nationwide', 'Pan-Nigerian',
   ARRAY['chicken', 'scotch bonnet', 'ginger', 'garlic', 'onion', 'seasoning'], ARRAY['Spicy', 'Juicy', 'Savoury'],
   'Chicken marinated in a bold pepper and spice blend, grilled or fried and finished in a fiery pepper sauce. A party and restaurant staple across Nigeria — the version at any given restaurant is often a point of pride.',
   ARRAY['jollof-rice', 'fried-rice', 'chips'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   4, 50, '/images/pepper-chicken.jpg'),
  ('D074', 'eba-ogbono', 'Eba and Ogbono', 'Eba na Ogbono',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['eba', 'ogbono soup'], ARRAY['Rich', 'Thick', 'Draw'],
   'The second most ordered combination in Nigerian restaurants — eba with ogbono soup. The thick, draw quality of the ogbono perfectly complements the density of eba. A deeply satisfying lunchtime staple at bukas nationwide.',
   ARRAY['eba', 'ogbono-soup'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 55, '/images/eba-ogbono.jpg'),
  ('D075', 'shinkafa-zogale', 'Shinkafa da Zogale', 'Shinkafa da Zogale (Hausa)',
   'Rice Dish', 'North', 'Hausa',
   ARRAY['rice', 'moringa leaves', 'groundnut oil', 'onion', 'pepper'], ARRAY['Earthy', 'Mild', 'Nutritious'],
   'A Northern Nigerian rice dish cooked with moringa (zogale) leaves, highly valued for its nutritional properties. A humble but deeply satisfying everyday meal in Hausa households, especially popular during moringa season.',
   ARRAY['fried-fish', 'chicken'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   2, 40, '/images/shinkafa-zogale.jpg'),
  ('D076', 'agbo', 'Agbo (Herbal Drink)', 'Agbo (Yoruba)',
   'Drink', 'South-West', 'Yoruba',
   ARRAY['bitter herbs', 'roots', 'bark', 'water'], ARRAY['Bitter', 'Medicinal', 'Strong'],
   'A traditional Yoruba herbal concoction brewed from bitter roots, bark, and herbs. Believed to have medicinal properties — used for malaria, stomach ailments, and general wellness. Sold by roadside vendors in small bottles across Lagos.',
   ARRAY[]::TEXT[],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 60, '/images/agbo.jpg'),
  ('D077', 'ogi-akamu', 'Ogi with Milk', 'Akamu (Igbo), Tom Brown',
   'Breakfast', 'Nationwide', 'Pan-Nigerian',
   ARRAY['corn pap', 'evaporated milk', 'sugar'], ARRAY['Creamy', 'Sweet', 'Smooth'],
   'Classic Nigerian breakfast pap enriched with evaporated milk and sugar. The milk transforms the slightly sour ogi into a creamy, comforting breakfast. A staple in schools, hospitals, and households across generations.',
   ARRAY['akara', 'moi-moi'],
   FALSE, TRUE, TRUE,
   FALSE, FALSE,
   0, 15, '/images/ogi-milk.jpg'),
  ('D078', 'coconut-candy', 'Coconut Candy', 'Agbon Didun (Yoruba)',
   'Snack', 'South-West / Nationwide', 'Pan-Nigerian',
   ARRAY['fresh coconut', 'sugar', 'ginger'], ARRAY['Sweet', 'Chewy', 'Coconutty'],
   'Hard caramelised coconut candy made from shredded fresh coconut cooked with sugar until solidified. Sold in triangular molds at bus stops and markets across Nigeria. A beloved childhood sweet with a satisfying chewy bite.',
   ARRAY[]::TEXT[],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 30, '/images/coconut-candy.jpg'),
  ('D079', 'roasted-plantain-groundnut', 'Roasted Plantain and Groundnut', 'Boli and Epa (Yoruba)',
   'Street Food', 'South-West / Nationwide', 'Pan-Nigerian',
   ARRAY['plantain', 'roasted groundnuts'], ARRAY['Smoky', 'Sweet', 'Nutty'],
   'Plantain roasted over charcoal until the skin chars and the flesh caramelises, served with roasted groundnuts. A simple, perfect street food pairing — the sweet charred plantain and the salty crunchy groundnuts complement each other completely.',
   ARRAY['groundnuts'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 20, '/images/roasted-plantain-groundnut.jpg'),
  ('D080', 'miyan-yakuwa', 'Miyan Yakuwa', 'Miyan Yakuwa (Hausa)',
   'Soup', 'North', 'Hausa',
   ARRAY['sorrel leaves (yakuwa)', 'groundnut paste', 'meat', 'dawadawa', 'pepper'], ARRAY['Sour', 'Rich', 'Earthy'],
   'A Northern Nigerian soup made with sorrel leaves giving it a characteristic sour flavour, enriched with groundnut paste. A daily staple in many Hausa households — simple to prepare and deeply satisfying alongside tuwo.',
   ARRAY['tuwo-shinkafa', 'tuwo-masara'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 35, '/images/miyan-yakuwa.jpg'),
  ('D081', 'okpa', 'Okpa (Bambara Nut Pudding)', 'Okpa (Igbo)',
   'Snack', 'South-East', 'Igbo (Enugu)',
   ARRAY['bambara nut flour', 'palm oil', 'pepper', 'crayfish', 'onion'], ARRAY['Dense', 'Savoury', 'Earthy'],
   'A protein-rich steamed pudding made from bambara nut flour, wrapped in leaves and sold by roadside vendors. An Enugu morning staple — the city''s unofficial breakfast food. Dense, filling, and deeply nourishing.',
   ARRAY['ogi'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   2, 60, '/images/okpa.jpg'),
  ('D082', 'native-jollof', 'Native Jollof (Palm Oil Rice)', 'Iwuk Edesi (Efik), Native Rice',
   'Rice Dish', 'South-South / South-East', 'Efik / Pan-Nigerian',
   ARRAY['rice', 'palm oil', 'assorted meat', 'crayfish', 'stockfish', 'periwinkle', 'pepper'], ARRAY['Rich', 'Smoky', 'Earthy'],
   'Rice cooked in palm oil with assorted meats and seafood — a rustic, deeply flavoured alternative to tomato-based jollof. Each culture has their version. Efik''s Iwuk Edesi is particularly celebrated for its complexity.',
   ARRAY['fried-fish', 'chicken'],
   FALSE, FALSE, TRUE,
   FALSE, TRUE,
   3, 55, '/images/native-jollof.jpg'),
  ('D083', 'eba-egusi-fish', 'Eba, Egusi and Fish', 'Nationwide classic',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['eba', 'egusi soup', 'catfish or stockfish'], ARRAY['Rich', 'Earthy', 'Savoury'],
   'The classic buka combination — eba, egusi soup enriched with whole catfish or stockfish. The fish adds a layer of depth and protein that elevates the standard egusi and eba pairing. The definitive Nigerian lunch.',
   ARRAY['eba', 'egusi-soup'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 65, '/images/eba-egusi-fish.jpg'),
  ('D084', 'nni-ji', 'Boiled Yam and Ofe', 'Nni Ji (Igbo)',
   'Breakfast', 'South-East', 'Igbo',
   ARRAY['yam', 'palm oil sauce', 'crayfish', 'stockfish'], ARRAY['Starchy', 'Savoury', 'Simple'],
   'Boiled yam chunks served with a simple but richly flavoured palm oil sauce with crayfish and stockfish. A classic Igbo breakfast and comfort meal — simple, grounding, and satisfying. Eaten with bare hands traditionally.',
   ARRAY['palm-oil-sauce'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 30, '/images/boiled-yam-ofe.jpg'),
  ('D085', 'robo', 'Robo (Groundnut Cake)', 'Robo (Hausa/Yoruba)',
   'Snack', 'North / Nationwide', 'Hausa',
   ARRAY['groundnut', 'sugar', 'ginger'], ARRAY['Sweet', 'Crunchy', 'Nutty'],
   'Crunchy groundnut brittle made by coating roasted groundnuts in hardened sugar and ginger syrup. Sold in small palm-sized pieces by street vendors. A popular roadside snack that satisfies both sweet and savoury cravings at once.',
   ARRAY['zobo', 'soft-drinks'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 30, '/images/robo.jpg'),
  ('D086', 'ayamase-ofada-combo', 'Ofada Rice and Ayamase Combo', 'Ofada Special',
   'Rice Dish', 'South-West', 'Yoruba',
   ARRAY['ofada rice', 'ayamase stew', 'assorted meat', 'boiled egg'], ARRAY['Smoky', 'Pungent', 'Rich'],
   'The complete ofada experience — local unpolished rice served in banana leaf with pungent ayamase stew, assorted meat, and boiled egg. An intensely flavoured meal that is becoming increasingly popular beyond the South-West.',
   ARRAY['beer', 'soft-drinks'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   5, 60, '/images/ofada-combo.jpg'),
  ('D087', 'miyan-toka', 'Miyan Toka (Ash Soup)', 'Miyan Toka (Hausa)',
   'Soup', 'North', 'Hausa',
   ARRAY['ash from burned baobab pods', 'meat', 'groundnut oil', 'pepper', 'onion'], ARRAY['Sour', 'Unique', 'Earthy'],
   'A uniquely Northern Nigerian soup made with ashes from burned baobab pods as a souring and thickening agent. One of the most distinctive and unusual soups in all of Nigerian cuisine — a true cultural relic of the North.',
   ARRAY['tuwo-shinkafa', 'tuwo-masara'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 45, '/images/miyan-toka.jpg'),
  ('D088', 'ofe-mgbam', 'Mgbam Soup', 'Ofe Mgbam (Igbo)',
   'Soup', 'South-East', 'Igbo',
   ARRAY['dried fish', 'uziza leaves', 'palm oil', 'crayfish', 'ogiri', 'pepper'], ARRAY['Pungent', 'Rich', 'Aromatic'],
   'A deeply flavoured Igbo soup starring dried fish and ogiri (fermented locust beans) as its main seasoning agents. The fermented notes from the ogiri create an intense umami depth that is characteristic of traditional Igbo cooking.',
   ARRAY['eba', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 50, '/images/ofe-mgbam.jpg'),
  ('D089', 'jollof-spaghetti', 'Nigerian Jollof Spaghetti', 'Jollof Spaghetti (Nationwide)',
   'Rice Dish', 'Nationwide', 'Pan-Nigerian',
   ARRAY['spaghetti', 'tomato', 'tatashe', 'onion', 'palm oil', 'seasoning', 'vegetables'], ARRAY['Savoury', 'Smoky', 'Tangy'],
   'Spaghetti cooked Nigerian-style in a tomato and pepper base — the pasta absorbs the jollof flavours just as rice would. A fusion dish that has become a Nigerian restaurant staple and a popular party alternative to jollof rice.',
   ARRAY['chicken', 'plantain', 'coleslaw'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 40, '/images/jollof-spaghetti.jpg'),
  ('D090', 'egusi-eba-snail', 'Egusi Soup with Snail', 'Ofe Egusi na Eju (Igbo)',
   'Soup', 'South-East / Nationwide', 'Pan-Nigerian',
   ARRAY['egusi', 'giant African snail', 'palm oil', 'leafy greens', 'crayfish'], ARRAY['Rich', 'Chewy', 'Earthy'],
   'Egusi soup elevated with the addition of giant African snails — a premium variant that is a favourite at celebrations and upscale bukas. The snail adds a luxurious, chewy texture contrast to the ground melon seed base.',
   ARRAY['pounded-yam', 'eba', 'fufu'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 70, '/images/egusi-snail.jpg'),
  ('D091', 'fried-fish', 'Nigerian Fried Fish', 'Eja Din Din (Yoruba), Azụ Eghe (Igbo)',
   'Protein', 'Nationwide', 'Pan-Nigerian',
   ARRAY['whole tilapia or croaker fish', 'pepper', 'onion', 'seasoning', 'oil'], ARRAY['Crispy', 'Spicy', 'Savoury'],
   'Whole fish marinated in a pepper and spice blend and deep-fried until crispy outside and moist inside. An essential accompaniment to Nigerian meals — no party spread is complete without a tray of fried fish.',
   ARRAY['jollof-rice', 'fried-rice', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 30, '/images/fried-fish.jpg'),
  ('D092', 'ponmo-stew', 'Ponmo Stew', 'Ponmo (Nationwide)',
   'Protein', 'Nationwide', 'Pan-Nigerian',
   ARRAY['cow skin (ponmo)', 'tomato', 'pepper', 'onion', 'palm oil', 'seasoning'], ARRAY['Chewy', 'Savoury', 'Rich'],
   'Cow skin (ponmo) cooked in a rich Nigerian tomato stew. Beloved for its unique chewy texture and the way it absorbs the stew''s flavours. Found in virtually every Nigerian buka — often the first protein to sell out.',
   ARRAY['jollof-rice', 'eba', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 60, '/images/ponmo.jpg'),
  ('D093', 'shaki-stew', 'Shaki (Tripe) Stew', 'Shaki (Nationwide)',
   'Protein', 'Nationwide', 'Pan-Nigerian',
   ARRAY['cow tripe (shaki)', 'tomato', 'pepper', 'onion', 'palm oil'], ARRAY['Chewy', 'Rich', 'Savoury'],
   'Cow tripe cooked slowly in tomato stew until tender. Its distinctive honeycomb texture absorbs the stew''s spices magnificently. A beloved offal dish that divides Nigerians — devotees consider it the best part of any assorted meat selection.',
   ARRAY['jollof-rice', 'eba', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 90, '/images/shaki.jpg'),
  ('D094', 'indomie', 'Nigerian-Style Indomie', 'Indomie (Nationwide)',
   'Street Food', 'Nationwide', 'Pan-Nigerian',
   ARRAY['instant noodles', 'egg', 'vegetables', 'pepper', 'seasoning'], ARRAY['Savoury', 'Spicy', 'Quick'],
   'Instant noodles prepared Nigerian-style — not as per packet instructions, but stir-fried with egg, vegetables, and pepper for a spicy, flavour-packed result. A universally beloved quick meal from students to executives.',
   ARRAY['fried-egg', 'plantain'],
   FALSE, TRUE, TRUE,
   FALSE, FALSE,
   3, 15, '/images/indomie.jpg'),
  ('D095', 'efo-elegusi', 'Efo Elegusi', 'Efo Elegusi (Yoruba)',
   'Soup', 'South-West', 'Yoruba',
   ARRAY['shoko leaves', 'egusi', 'palm oil', 'assorted meat', 'locust beans', 'crayfish'], ARRAY['Rich', 'Leafy', 'Earthy'],
   'A Yoruba soup combining shoko leaves with egusi — the melon seeds thicken the soup while the vegetables add freshness. Less common than efo riro but equally beloved, it represents the intersection of Yoruba vegetable and nut-based soup traditions.',
   ARRAY['amala', 'pounded-yam', 'eba'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 50, '/images/efo-elegusi.jpg'),
  ('D096', 'apon-soup', 'Apon Soup', 'Apon (Yoruba)',
   'Soup', 'South-West', 'Yoruba',
   ARRAY['locust beans', 'palm oil', 'assorted meat', 'dried fish', 'pepper'], ARRAY['Pungent', 'Earthy', 'Strong'],
   'A bold Yoruba soup where locust beans (iru) are the star ingredient rather than just a seasoning. Intensely pungent and flavourful, it is a divisive but beloved dish with devoted fans who consider its strong aroma its greatest virtue.',
   ARRAY['amala', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 40, '/images/apon-soup.jpg'),
  ('D097', 'oha-bitter-leaf-combo', 'Oha and Bitter Leaf Combination', 'Ofe Ji Oku (Igbo)',
   'Soup', 'South-East', 'Igbo',
   ARRAY['oha leaves', 'bitter leaf', 'cocoyam', 'palm oil', 'assorted meat'], ARRAY['Complex', 'Rich', 'Aromatic'],
   'A prestigious Igbo soup combining both oha and bitter leaves with cocoyam as thickener. The combination of the two leaves creates a complexity that neither achieves alone — served at weddings, funerals, and title-taking ceremonies.',
   ARRAY['pounded-yam', 'fufu'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 80, '/images/oha-bitter-combo.jpg'),
  ('D098', 'nkpokiri-soup', 'Dry Fish Soup', 'Ofe Nkpokiri (Igbo)',
   'Soup', 'South-East', 'Igbo',
   ARRAY['dried catfish (nkpokiri)', 'palm oil', 'uziza leaves', 'crayfish', 'ogiri'], ARRAY['Smoky', 'Pungent', 'Rich'],
   'An Igbo soup built around dried, smoked catfish — the intense smokiness of the nkpokiri permeates every element. A taste of traditional Igbo cooking before refrigeration, now cherished as a link to culinary heritage.',
   ARRAY['eba', 'pounded-yam', 'fufu'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 45, '/images/nkpokiri-soup.jpg'),
  ('D099', 'ogi-baba', 'Ogi Baba (Thick Pap)', 'Ogi Baba (Yoruba)',
   'Breakfast', 'South-West', 'Yoruba',
   ARRAY['fermented corn', 'water'], ARRAY['Sour', 'Thick', 'Filling'],
   'A thicker, denser version of regular ogi — cooked longer until it sets almost like a pudding. Eaten with a spoon rather than drunk, and typically served with akara. A Yoruba breakfast tradition with more body and sustenance.',
   ARRAY['akara', 'moi-moi'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 20, '/images/ogi-baba.jpg'),
  ('D100', 'kondre', 'Kondre', 'Kondre (Bamileke — Nigerian variation)',
   'Soup', 'South-West / Pan-Nigerian', 'Pan-Nigerian',
   ARRAY['unripe plantain', 'goat meat', 'huckleberry leaves', 'palm oil', 'crayfish'], ARRAY['Rich', 'Earthy', 'Complex'],
   'A hearty soup made with unripe plantain chunks that break down to thicken the broth, combined with goat meat and huckleberry leaves. A lesser-known but deeply satisfying dish gaining popularity in Lagos restaurants.',
   ARRAY['eba', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   3, 70, '/images/kondre.jpg'),
  ('D101', 'small-chops', 'Small Chops', 'Small Chops (Nationwide)',
   'Snack', 'Nationwide', 'Pan-Nigerian',
   ARRAY['puff puff', 'spring rolls', 'samosa', 'chicken wings', 'peppered snail'], ARRAY['Mixed', 'Crispy', 'Savoury'],
   'An assortment of bite-sized Nigerian party snacks — puff puff, spring rolls, samosa, peppered snail, chicken wings. The most ordered item at Nigerian parties and events. The success of any gathering is judged partly by small chops quality.',
   ARRAY['zobo', 'soft-drinks'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 60, '/images/small-chops.jpg'),
  ('D102', 'ukwa', 'Ukwa (African Breadfruit)', 'Ukwa (Igbo)',
   'Snack', 'South-East', 'Igbo',
   ARRAY['African breadfruit seeds', 'palm oil', 'crayfish', 'utazi leaves', 'pepper'], ARRAY['Earthy', 'Rich', 'Nutty'],
   'Boiled African breadfruit seeds cooked in palm oil with crayfish and utazi leaves. A culturally significant Igbo dish often served at traditional events and title-taking ceremonies. Dense, earthy, and filling.',
   ARRAY['palm-wine'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   2, 90, '/images/ukwa.jpg'),
  ('D103', 'obe-ata', 'Nigerian Tomato Stew', 'Obe Ata (Yoruba), Ofe Anu (Igbo)',
   'Soup', 'Nationwide', 'Pan-Nigerian',
   ARRAY['tomato', 'tatashe', 'scotch bonnet', 'onion', 'palm oil', 'seasoning'], ARRAY['Rich', 'Savoury', 'Tangy'],
   'Nigeria''s base stew — the foundation of countless meals. Made from blended tomatoes, peppers, and onions cooked in palm oil until the water evaporates and the oil floats to the top. Every Nigerian cook has their own signature version.',
   ARRAY['white-rice', 'eba', 'pounded-yam', 'fried-plantain'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   3, 45, '/images/obe-ata.jpg'),
  ('D104', 'white-rice-stew', 'White Rice and Stew', 'Iresi Funfun (Yoruba), Osikapa na Ofe (Igbo)',
   'Rice Dish', 'Nationwide', 'Pan-Nigerian',
   ARRAY['parboiled rice', 'tomato stew', 'assorted meat'], ARRAY['Simple', 'Savoury', 'Filling'],
   'Plain boiled rice served with rich tomato stew and meat. The simplest and most universal Nigerian meal — eaten at every social class and occasion. The quality of the stew is everything, and Nigerians are serious judges.',
   ARRAY['tomato-stew', 'fried-plantain', 'fried-fish'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 30, '/images/white-rice-stew.jpg'),
  ('D105', 'ofe-ugba', 'Ugba Soup', 'Ofe Ugba (Igbo)',
   'Soup', 'South-East', 'Igbo',
   ARRAY['ugba (fermented oil bean)', 'palm oil', 'uziza leaves', 'crayfish', 'assorted meat'], ARRAY['Pungent', 'Rich', 'Fermented'],
   'A bold Igbo soup with ugba as the star ingredient — the fermented oil bean gives it an intensely pungent, complex flavour. Far less common than egusi or ofe onugbu, it is a connoisseur''s dish highly prized by traditional Igbo food lovers.',
   ARRAY['eba', 'pounded-yam'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 45, '/images/ofe-ugba.jpg'),
  ('D106', 'afia-efere', 'Afia Efere (White Soup Efik)', 'Afia Efere (Efik)',
   'Soup', 'South-South', 'Efik',
   ARRAY['chicken', 'yam', 'crayfish', 'utazi', 'pepper', 'onion'], ARRAY['Light', 'Mild', 'Aromatic'],
   'The Efik version of white soup — a clear, light broth made without palm oil, thickened with yam and loaded with chicken. Elegant and refined in character, it is served at Efik ceremonies as a prestigious offering.',
   ARRAY['pounded-yam', 'fufu'],
   FALSE, FALSE, TRUE,
   FALSE, FALSE,
   2, 55, '/images/afia-efere.jpg'),
  ('D107', 'abak-soup', 'Abak Soup', 'Abak (Efik/Ibibio)',
   'Soup', 'South-South', 'Efik / Ibibio',
   ARRAY['palm nut', 'assorted meat', 'periwinkle', 'crayfish', 'spices'], ARRAY['Rich', 'Earthy', 'Aromatic'],
   'A rich Efik/Ibibio palm nut soup, simpler than Abak Atama but equally satisfying. A daily staple in many South-South homes, with each family having their own balance of spices and protein.',
   ARRAY['pounded-yam', 'eba', 'starch'],
   FALSE, FALSE, TRUE,
   FALSE, TRUE,
   3, 70, '/images/abak-soup.jpg'),
  ('D108', 'garri-groundnut', 'Garri and Groundnut', 'Garri na Epa (Yoruba), Garri na Ekpa (Igbo)',
   'Snack', 'Nationwide', 'Pan-Nigerian',
   ARRAY['garri', 'groundnuts', 'sugar', 'cold water'], ARRAY['Crunchy', 'Sweet-Salty', 'Refreshing'],
   'Dry garri soaked in cold water with groundnuts, sugar, and sometimes milk — the unofficial student meal and afternoon snack of Nigeria. Humble, deeply satisfying, and eaten across all social classes. A cultural institution.',
   ARRAY['groundnuts', 'coconut', 'sugar'],
   TRUE, TRUE, TRUE,
   FALSE, FALSE,
   0, 5, '/images/garri-groundnut.jpg');

-- RESTAURANTS SCHEMA (Unit 3 prep)
CREATE TABLE IF NOT EXISTS restaurants (
  restaurant_id    SERIAL        PRIMARY KEY,
  slug             VARCHAR(150)  NOT NULL UNIQUE,
  name             VARCHAR(200)  NOT NULL,
  type             VARCHAR(50),
  city             VARCHAR(100)  NOT NULL,
  neighbourhood    VARCHAR(100),
  address          TEXT,
  latitude         DECIMAL(9,6),
  longitude        DECIMAL(9,6),
  phone            VARCHAR(20),
  price_range      VARCHAR(10),
  delivery_available BOOLEAN     DEFAULT FALSE,
  verified         BOOLEAN       DEFAULT FALSE,
  claimed          BOOLEAN       DEFAULT FALSE,
  rating           DECIMAL(2,1)  DEFAULT 0.0,
  accuracy_score   SMALLINT      DEFAULT 0,
  created_at       TIMESTAMPTZ   DEFAULT NOW(),
  updated_at       TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS restaurant_dishes (
  id             SERIAL   PRIMARY KEY,
  restaurant_id  INTEGER  REFERENCES restaurants(restaurant_id) ON DELETE CASCADE,
  dish_id        VARCHAR(6) REFERENCES dishes(dish_id) ON DELETE CASCADE,
  available      BOOLEAN  DEFAULT TRUE,
  price_ngn      INTEGER,
  UNIQUE(restaurant_id, dish_id)
);

CREATE TABLE IF NOT EXISTS reviews (
  review_id       SERIAL      PRIMARY KEY,
  restaurant_id   INTEGER     REFERENCES restaurants(restaurant_id) ON DELETE CASCADE,
  dish_id         VARCHAR(6)  REFERENCES dishes(dish_id),
  dish_accuracy   VARCHAR(10) CHECK (dish_accuracy IN ('yes','no','partial')),
  food_quality    SMALLINT    CHECK (food_quality BETWEEN 1 AND 5),
  value_for_money SMALLINT    CHECK (value_for_money BETWEEN 1 AND 5),
  service         SMALLINT    CHECK (service BETWEEN 1 AND 5),
  review_text     TEXT,
  visit_date      DATE,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- USEFUL QUERIES
-- Find all Igbo soups:
-- SELECT dish_id, name_english, slug FROM dishes WHERE category='Soup' AND ethnic_group ILIKE '%Igbo%';
-- Find all halal dishes:
-- SELECT dish_id, name_english FROM dishes WHERE halal = TRUE;
-- Find vegan dishes:
-- SELECT dish_id, name_english, category FROM dishes WHERE vegan = TRUE ORDER BY category;
-- Find spicy dishes (level 4+):
-- SELECT dish_id, name_english, spice_level FROM dishes WHERE spice_level >= 4 ORDER BY spice_level DESC;
-- Find Northern dishes:
-- SELECT dish_id, name_english, ethnic_group FROM dishes WHERE region ILIKE '%North%';
-- Search by ingredient:
-- SELECT dish_id, name_english FROM dishes WHERE 'palm oil' = ANY(primary_ingredients);